<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home'=>'Inicio',
  'About'=>'Nosotros',
  'Contact'=>'Contacto',
  'Login'=>'Ingresar',
  'Logout'=>'Salir',
  'Information'=>'Informacion',
  'Price'=>'Precio',
  'Name'=>'Nombre',
  'Tags'=>'Etiquetas',
  'Main products' => 'Productos destacados',
  'Brands' => 'Marcas',
  'No brands to show' => 'No hay marcas para mostrar',
  'No stores to show' => 'No hay tiendas para mostrar',
  'Our stores' => 'Nuestras tiendas',
  'Our price' => 'Nuestro precio',
  'No categories to show' => 'No hay categorias disponibles',
  'No products to show' => 'No hay productos para mostrar',
  'No shops to show' => 'No hay comercios relacionados en esta categoria',
  'Categories' => 'Categorias',
  'Contact us'=>'Contactanos',
  'About us'=>'Acerca de nosotros',
  'Please add content to this page'=>'Por favor agregue contenido para esta página.',
  'New products'=>'Productos nuevos',
  'Other products in the same category'=>'Otros productos de la misma categoria',
  'Other related shops'=>'Otros comercios relacionados',
  'More info'=>'Detalles',
  'Specifications'=>'Especificaciones',
  'Add new specification'=>'A&ntilde;adir especificaci&oacute;n',
  'Refresh specifications'=>'Refrescar especificaciones',
  'Profile'=>'Descripcion',
  'Close'=>'Cerrar',
  'Colors'=>'Colores',
  'Yellow'=>'Amarillo',
  'Blue'=>'Azul',
  'In stock'=>'Disponible',
  'Not In stock'=>'No disponible',
  'Sort by'=>'Ordenar por',
  'Reset'=>'Limpiar',
  'New'=>'Nuevo !',
  'Filter New'=>'Nuevos',
  'Type'=>'Tipo',
  'Search'=>'Buscar',
  'Customer service'=>'Servicio al cliente',
  'Go'=>'Ir',
  'Save'=>'Guardar',
  'Create'=>'Crear',
  'Phrase of the day'=>'Frase del dia',
  'Video of the month'=>'Video del mes',
  'No posts to show'=>'Aun no hay posts creados',
  'Map'=>'Mapa',
  'Select all/none'=>'Seleccionar todos',
  'Find'=>'Buscar',
);
