<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Information'=>'Informacion',
  'Price'=>'Precio',
  'Name'=>'Nombre',
  'Content'=>'Contenido',
  'Tags'=>'Etiquetas',
  'Categories' => 'Categorias',
  'In stock'=>'Disponible',
  'Not In stock'=>'No disponible',
  'New'=>'Nuevo !' ,
  'Type'=>'Tipo',
  'Save'=>'Guardar',
  'Create'=>'Nuevo',
  'Add information'=>'Añadir información',
  'Delete'=>'Eliminar',
  'Delete selected angles'=>'¿ Eliminar angulos seleccionados ?',
  'Do you wish delete selected specifications?'=>'¿ Quiere eliminar elementos seleccionados ?',
  'Angles images'=>'Angulos del producto',
  'Product information'=>'Información del producto',
  'Product specifications'=>'Especificaciones del producto',
  'Main image'=>'Imagen principal',
  'You can select any images'=>'puede seleccionar la cantidad de imágenes que desee',
  'Do you wish to delete, the selected angles ?'=>'¿ Desea eliminar los angulos seleccionados ?',
  'Description'=>'Descripción',
  'Title'=>'Título',
  'Position'=>'Posición',
  'View product'=>'Visualizar anuncio',
  'Could not refresh the specifications'=>'No se pudieron refrescar las especifiacaciones, reporte a sistemas',
);
